example-pkg := "hello"
spec-example-pkg := "gcc"

eval:
    @nickel eval {{example-pkg}}.ncl

json:
    @nickel export --format json {{example-pkg}}.ncl | tee export/json/{{example-pkg}}.ruyi.json 

yaml:
    @nickel export --format yaml {{example-pkg}}.ncl | tee export/yaml/{{example-pkg}}.ruyi.yaml  

spec:
    @nickel export --format text --field {{spec-example-pkg}}-spec {{spec-example-pkg}}.ncl | tee export/spec/{{spec-example-pkg}}.ruyi.spec  
